export const cropTypes = [
    "Cereals (Rice, Wheat, Maize, etc.)",
    "Pulses (Chana, Moong, Toor, etc.)",
    "Oilseeds (Soybean, Mustard, Groundnut, etc.)",
    "Vegetables (Tomato, Onion, Potato, etc.)",
    "Fruits (Mango, Banana, Apple, etc.)",
    "Spices (Chilli, Turmeric, Cumin, etc.)",
    "Commercial Crops (Cotton, Sugarcane, Tobacco, etc.)",
    "Dairy Products",
    "Poultry Products",
    "Fisheries",
    "Other (Please specify)"
  ];

  export const commodityOptions = [
    "Grains (Corn, Wheat, Soybeans)",
    "Fruits (Apples, Berries, Citrus)",
    "Vegetables (Potatoes, Tomatoes, Leafy Greens)",
    "Nuts (Almonds, Walnuts, Pecans)",
    "Dairy",
    "Livestock",
    "Other"
  ];

export const investmentOptions = [
    "Cold Storage Facility",
    "Processing Equipment",
    "Packaging Line",
    "Transportation Vehicles",
    "Value-Added Product Development",
    "Food Safety Certification",
    "Market Access Infrastructure"
  ];

    export const cropInvestments = [
      {
        id: 1,
        cropName: "Corn",
        totalRequested: 15000,
        approvedAmount: 12000,
        status: "approved",
        date: "2023-10-15",
        purpose: "Pre-harvest equipment"
      },
      {
        id: 2,
        cropName: "Soybean",
        totalRequested: 8000,
        approvedAmount: 5000,
        status: "partial",
        date: "2023-09-28",
        purpose: "Irrigation system"
      },
      {
        id: 3,
        cropName: "Wheat",
        totalRequested: 10000,
        approvedAmount: 0,
        status: "rejected",
        date: "2023-11-02",
        purpose: "Storage facility"
      },
      {
        id: 4,
        cropName: "Tomatoes",
        totalRequested: 5000,
        approvedAmount: 5000,
        status: "approved",
        date: "2023-08-20",
        purpose: "Greenhouse setup"
      },
      {
        id: 5,
        cropName: "Apples",
        totalRequested: 20000,
        approvedAmount: null,
        status: "pending",
        date: "2023-12-10",
        purpose: "Cold storage"
      },
      {
        id: 6,
        cropName: "Cotton",
        totalRequested: 12000,
        approvedAmount: 8000,
        status: "partial",
        date: "2023-07-15",
        purpose: "Harvesting tools"
      },
      {
        id: 7,
        cropName: "Potatoes",
        totalRequested: 7000,
        approvedAmount: 7000,
        status: "approved",
        date: "2023-06-22",
        purpose: "Seed purchase"
      },
      {
        id: 8,
        cropName: "Berries",
        totalRequested: 9000,
        approvedAmount: null,
        status: "pending",
        date: "2024-01-05",
        purpose: "Drip irrigation"
      }
    ];

    export const postHarvestInvestments = [
      {
        id: 1,
        cropName: "Corn",
        bushels: 15000,
        totalRequested: 25000,
        approvedAmount: 20000,
        status: "approved",
        date: "2023-10-15",
        facilityType: "Cold Storage",
        storageCapacity: 20000,
        purpose: "Temperature-controlled storage"
      },
      {
        id: 2,
        cropName: "Soybean",
        bushels: 8000,
        totalRequested: 15000,
        approvedAmount: 10000,
        status: "partial",
        date: "2023-09-28",
        facilityType: "Grain Bin",
        storageCapacity: 10000,
        purpose: "On-farm grain storage"
      },
      {
        id: 3,
        cropName: "Wheat",
        bushels: 12000,
        totalRequested: 22000,
        approvedAmount: 22000,
        status: "approved",
        date: "2023-08-10",
        facilityType: "Warehouse",
        storageCapacity: 25000,
        purpose: "Bulk storage for export"
      },
      {
        id: 4,
        cropName: "Barley",
        bushels: 6000,
        totalRequested: 12000,
        approvedAmount: 8000,
        status: "partial",
        date: "2023-07-22",
        facilityType: "Silo",
        storageCapacity: 15000,
        purpose: "Feed grain storage"
      },
      {
        id: 5,
        cropName: "Rice",
        bushels: 20000,
        totalRequested: 30000,
        approvedAmount: 30000,
        status: "approved",
        date: "2023-11-01",
        facilityType: "Cold Storage",
        storageCapacity: 30000,
        purpose: "High-humidity storage"
      },
      {
        id: 6,
        cropName: "Oats",
        bushels: 5000,
        totalRequested: 9000,
        approvedAmount: 6000,
        status: "partial",
        date: "2023-06-30",
        facilityType: "Shed",
        storageCapacity: 7000,
        purpose: "Short-term storage"
      },
      {
        id: 7,
        cropName: "Sorghum",
        bushels: 14000,
        totalRequested: 26000,
        approvedAmount: 26000,
        status: "approved",
        date: "2023-10-05",
        facilityType: "Grain Elevator",
        storageCapacity: 27000,
        purpose: "Bulk grain handling"
      },
      {
        id: 8,
        cropName: "Sunflower",
        bushels: 4000,
        totalRequested: 8000,
        approvedAmount: 4000,
        status: "partial",
        date: "2023-08-19",
        facilityType: "Warehouse",
        storageCapacity: 10000,
        purpose: "Oil seed storage"
      },
      {
        id: 9,
        cropName: "Peanut",
        bushels: 10000,
        totalRequested: 18000,
        approvedAmount: 18000,
        status: "approved",
        date: "2023-09-14",
        facilityType: "Cold Storage",
        storageCapacity: 20000,
        purpose: "Moisture-controlled storage"
      },
      {
        id: 10,
        cropName: "Cotton",
        bushels: 7000,
        totalRequested: 14000,
        approvedAmount: 14000,
        status: "approved",
        date: "2023-07-07",
        facilityType: "Warehouse",
        storageCapacity: 15000,
        purpose: "Bale storage"
      },
      {
        id: 11,
        cropName: "Canola",
        bushels: 9000,
        totalRequested: 16000,
        approvedAmount: 12000,
        status: "partial",
        date: "2023-06-15",
        facilityType: "Grain Bin",
        storageCapacity: 13000,
        purpose: "Seed oil storage"
      },
      {
        id: 12,
        cropName: "Lentils",
        bushels: 3000,
        totalRequested: 6000,
        approvedAmount: 6000,
        status: "approved",
        date: "2023-11-20",
        facilityType: "Shed",
        storageCapacity: 7000,
        purpose: "Dry legume storage"
      },
      {
        id: 13,
        cropName: "Millet",
        bushels: 4500,
        totalRequested: 7500,
        approvedAmount: 4000,
        status: "partial",
        date: "2023-09-09",
        facilityType: "Silo",
        storageCapacity: 8000,
        purpose: "Small-grain storage"
      },
      {
        id: 14,
        cropName: "Quinoa",
        bushels: 2500,
        totalRequested: 5000,
        approvedAmount: 5000,
        status: "approved",
        date: "2023-08-01",
        facilityType: "Cold Storage",
        storageCapacity: 6000,
        purpose: "Specialty grain storage"
      },
      {
        id: 15,
        cropName: "Alfalfa",
        bushels: 11000,
        totalRequested: 20000,
        approvedAmount: 16000,
        status: "partial",
        date: "2023-10-25",
        facilityType: "Shed",
        storageCapacity: 12000,
        purpose: "Forage storage"
      },
      {
        id: 16,
        cropName: "Flaxseed",
        bushels: 3500,
        totalRequested: 7000,
        approvedAmount: 7000,
        status: "approved",
        date: "2023-11-10",
        facilityType: "Grain Bin",
        storageCapacity: 8000,
        purpose: "Oilseed storage"
      },
      {
        id: 17,
        cropName: "Hemp",
        bushels: 6000,
        totalRequested: 12000,
        approvedAmount: 10000,
        status: "partial",
        date: "2023-07-29",
        facilityType: "Warehouse",
        storageCapacity: 13000,
        purpose: "Fiber and seed storage"
      },
      {
        id: 18,
        cropName: "Chickpeas",
        bushels: 5500,
        totalRequested: 10000,
        approvedAmount: 10000,
        status: "approved",
        date: "2023-09-01",
        facilityType: "Silo",
        storageCapacity: 11000,
        purpose: "Pulses storage"
      },
      {
        id: 19,
        cropName: "Beans",
        bushels: 7800,
        totalRequested: 13000,
        approvedAmount: 9000,
        status: "partial",
        date: "2023-08-14",
        facilityType: "Cold Storage",
        storageCapacity: 14000,
        purpose: "Protein-rich crop storage"
      },
      {
        id: 20,
        cropName: "Rye",
        bushels: 9500,
        totalRequested: 17000,
        approvedAmount: 17000,
        status: "approved",
        date: "2023-10-02",
        facilityType: "Grain Elevator",
        storageCapacity: 18000,
        purpose: "Export-ready storage"
      }
    ];
    export const preHarvestInvestments = [
      {
        id: 1,
        cropName: "Corn",
        bushels: 15000,
        totalRequested: 25000,
        approvedAmount: 20000,
        status: "approved",
        date: "2023-10-15",
        facilityType: "Cold Storage",
        storageCapacity: 20000,
        purpose: "Temperature-controlled storage"
      },
      {
        id: 2,
        cropName: "Soybean",
        bushels: 8000,
        totalRequested: 15000,
        approvedAmount: 10000,
        status: "partial",
        date: "2023-09-28",
        facilityType: "Grain Bin",
        storageCapacity: 10000,
        purpose: "On-farm grain storage"
      },
      {
        id: 3,
        cropName: "Wheat",
        bushels: 12000,
        totalRequested: 22000,
        approvedAmount: 22000,
        status: "approved",
        date: "2023-08-10",
        facilityType: "Warehouse",
        storageCapacity: 25000,
        purpose: "Bulk storage for export"
      },
      {
        id: 4,
        cropName: "Barley",
        bushels: 6000,
        totalRequested: 12000,
        approvedAmount: 8000,
        status: "partial",
        date: "2023-07-22",
        facilityType: "Silo",
        storageCapacity: 15000,
        purpose: "Feed grain storage"
      },
      {
        id: 5,
        cropName: "Rice",
        bushels: 20000,
        totalRequested: 30000,
        approvedAmount: 30000,
        status: "approved",
        date: "2023-11-01",
        facilityType: "Cold Storage",
        storageCapacity: 30000,
        purpose: "High-humidity storage"
      },
      {
        id: 6,
        cropName: "Oats",
        bushels: 5000,
        totalRequested: 9000,
        approvedAmount: 6000,
        status: "partial",
        date: "2023-06-30",
        facilityType: "Shed",
        storageCapacity: 7000,
        purpose: "Short-term storage"
      },
      {
        id: 7,
        cropName: "Sorghum",
        bushels: 14000,
        totalRequested: 26000,
        approvedAmount: 26000,
        status: "approved",
        date: "2023-10-05",
        facilityType: "Grain Elevator",
        storageCapacity: 27000,
        purpose: "Bulk grain handling"
      },
      {
        id: 8,
        cropName: "Sunflower",
        bushels: 4000,
        totalRequested: 8000,
        approvedAmount: 4000,
        status: "partial",
        date: "2023-08-19",
        facilityType: "Warehouse",
        storageCapacity: 10000,
        purpose: "Oil seed storage"
      },
      {
        id: 9,
        cropName: "Peanut",
        bushels: 10000,
        totalRequested: 18000,
        approvedAmount: 18000,
        status: "approved",
        date: "2023-09-14",
        facilityType: "Cold Storage",
        storageCapacity: 20000,
        purpose: "Moisture-controlled storage"
      },
      {
        id: 10,
        cropName: "Cotton",
        bushels: 7000,
        totalRequested: 14000,
        approvedAmount: 14000,
        status: "approved",
        date: "2023-07-07",
        facilityType: "Warehouse",
        storageCapacity: 15000,
        purpose: "Bale storage"
      },
      {
        id: 11,
        cropName: "Canola",
        bushels: 9000,
        totalRequested: 16000,
        approvedAmount: 12000,
        status: "partial",
        date: "2023-06-15",
        facilityType: "Grain Bin",
        storageCapacity: 13000,
        purpose: "Seed oil storage"
      },
      {
        id: 12,
        cropName: "Lentils",
        bushels: 3000,
        totalRequested: 6000,
        approvedAmount: 6000,
        status: "approved",
        date: "2023-11-20",
        facilityType: "Shed",
        storageCapacity: 7000,
        purpose: "Dry legume storage"
      },
      {
        id: 13,
        cropName: "Millet",
        bushels: 4500,
        totalRequested: 7500,
        approvedAmount: 4000,
        status: "partial",
        date: "2023-09-09",
        facilityType: "Silo",
        storageCapacity: 8000,
        purpose: "Small-grain storage"
      },
      {
        id: 14,
        cropName: "Quinoa",
        bushels: 2500,
        totalRequested: 5000,
        approvedAmount: 5000,
        status: "approved",
        date: "2023-08-01",
        facilityType: "Cold Storage",
        storageCapacity: 6000,
        purpose: "Specialty grain storage"
      },
      {
        id: 15,
        cropName: "Alfalfa",
        bushels: 11000,
        totalRequested: 20000,
        approvedAmount: 16000,
        status: "partial",
        date: "2023-10-25",
        facilityType: "Shed",
        storageCapacity: 12000,
        purpose: "Forage storage"
      },
      {
        id: 16,
        cropName: "Flaxseed",
        bushels: 3500,
        totalRequested: 7000,
        approvedAmount: 7000,
        status: "approved",
        date: "2023-11-10",
        facilityType: "Grain Bin",
        storageCapacity: 8000,
        purpose: "Oilseed storage"
      },
      {
        id: 17,
        cropName: "Hemp",
        bushels: 6000,
        totalRequested: 12000,
        approvedAmount: 10000,
        status: "partial",
        date: "2023-07-29",
        facilityType: "Warehouse",
        storageCapacity: 13000,
        purpose: "Fiber and seed storage"
      },
      {
        id: 18,
        cropName: "Chickpeas",
        bushels: 5500,
        totalRequested: 10000,
        approvedAmount: 10000,
        status: "approved",
        date: "2023-09-01",
        facilityType: "Silo",
        storageCapacity: 11000,
        purpose: "Pulses storage"
      },
      {
        id: 19,
        cropName: "Beans",
        bushels: 7800,
        totalRequested: 13000,
        approvedAmount: 9000,
        status: "partial",
        date: "2023-08-14",
        facilityType: "Cold Storage",
        storageCapacity: 14000,
        purpose: "Protein-rich crop storage"
      },
      {
        id: 20,
        cropName: "Rye",
        bushels: 9500,
        totalRequested: 17000,
        approvedAmount: 17000,
        status: "approved",
        date: "2023-10-02",
        facilityType: "Grain Elevator",
        storageCapacity: 18000,
        purpose: "Export-ready storage"
      }
    ];
    

export const farmingName = [
  { id: 1, name: "Rice", number: 12 },
  { id: 2, name: "Wheat", number: 34 },
  { id: 3, name: "Corn", number: 7 },
  { id: 4, name: "Soybean", number: 91 },
  { id: 5, name: "Barley", number: 25 },
  { id: 6, name: "Cotton", number: 63 },
  { id: 8, name: "Tomato", number: 76 },
  { id: 9, name: "Sugarcane", number: 19 },
  { id: 10, name: "Coffee", number: 52 },
  { id: 11, name: "Tea", number: 84 },
  { id: 12, name: "Banana", number: 3 },
  { id: 13, name: "Apple", number: 67 },
  { id: 14, name: "Grapes", number: 29 },
  { id: 15, name: "Olive", number: 41 },
  { id: 16, name: "Pepper", number: 58 },
  { id: 17, name: "Sunflower", number: 95 },
  { id: 18, name: "Carrot", number: 16 },
  { id: 19, name: "Onion", number: 72 },
  { id: 20, name: "Cucumber", number: 37 }
]


export const preharveststatus = [
  {
    fullName: "John Smith",
    ssn: "123-45-6789",
    dob: "1980-05-15",
    phone: "(555) 123-4567",
    email: "john.smith@example.com",
    residentialAddress: "123 Farm Rd, Ruraltown, ST 12345",
    mailingAddress: "PO Box 123, Ruraltown, ST 12345",
    citizenshipStatus: "US Citizen",
    businessName: "Smith Family Farms",
    entityType: "Sole Proprietorship",
    ein: "12-3456789",
    usdaFarmNumber: "USDA123456",
    farmLocation: "456 Agriculture Ave, Farmville, ST 67890",
    yearsInOperation: 15,
    annualIncome: 125000,
    previousLoans: "Yes - Farm Credit Services 2018",
    landStatus: "Owned",
    landSize: 120,
    crops: ["Corn"],
    areaPerCrop: "40 acres each",
    irrigationType: "Center Pivot",
    equipmentOwned: "Tractor, Combine, Planter",
    soilType: "Loam",
    practices: "Crop Rotation, No-Till",
    loanAmount: 75000,
    loanPurpose: "Equipment Purchase",
    loanTerm: "5 years",
    loanType: "Equipment Loan",
    disbursementDate: "2023-06-01",
    expectedYield: "200 bu/acre Corn",
    repaymentSource: "Crop Sales",
    cropInsurance: "Yes - Multi-Peril",
    bankName: "Farmers National Bank",
    accountNumber: "987654321",
    routingNumber: "123456789",
    creditScore: 720,
    agree: true
  },
  {
    fullName: "Maria Garcia",
    ssn: "234-56-7890",
    dob: "1975-08-22",
    phone: "(555) 234-5678",
    email: "maria.garcia@example.com",
    residentialAddress: "789 Orchard Ln, Grovetown, ST 23456",
    mailingAddress: "Same as residential",
    citizenshipStatus: "Permanent Resident",
    businessName: "Garcia Orchards",
    entityType: "LLC",
    ein: "23-4567890",
    usdaFarmNumber: "USDA234567",
    farmLocation: "789 Orchard Ln, Grovetown, ST 23456",
    yearsInOperation: 8,
    annualIncome: 98000,
    previousLoans: "No",
    landStatus: "Leased",
    landSize: 80,
    crops: ["Apples"],
    areaPerCrop: "50 acres Apples, 30 acres Peaches",
    irrigationType: "Drip",
    equipmentOwned: "Tractor, Sprayer",
    soilType: "Sandy Loam",
    practices: "Integrated Pest Management",
    loanAmount: 45000,
    loanPurpose: "Orchard Expansion",
    loanTerm: "7 years",
    loanType: "Farm Ownership",
    disbursementDate: "2023-07-15",
    expectedYield: "800 bushels/acre Apples",
    repaymentSource: "Fruit Sales",
    cropInsurance: "Yes - Crop Hail",
    bankName: "AgriBank",
    accountNumber: "876543210",
    routingNumber: "234567890",
    creditScore: 690,
    agree: true
  },
  {
    fullName: "Robert Johnson",
    ssn: "345-67-8901",
    dob: "1965-03-10",
    phone: "(555) 345-6789",
    email: "robert.johnson@example.com",
    residentialAddress: "456 Ranch Rd, Countryside, ST 34567",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Johnson Cattle Co.",
    entityType: "Partnership",
    ein: "34-5678901",
    usdaFarmNumber: "USDA345678",
    farmLocation: "456 Ranch Rd, Countryside, ST 34567",
    yearsInOperation: 25,
    annualIncome: 185000,
    previousLoans: "Yes - FSA Direct Loan 2020",
    landStatus: "Owned",
    landSize: 500,
    crops: ["Pasture"],
    areaPerCrop: "300 acres Pasture, 200 acres Hay",
    irrigationType: "Flood",
    equipmentOwned: "Tractor, Baler, Cattle Trailer",
    soilType: "Clay Loam",
    practices: "Rotational Grazing",
    loanAmount: 120000,
    loanPurpose: "Livestock Purchase",
    loanTerm: "10 years",
    loanType: "Operating Loan",
    disbursementDate: "2023-08-01",
    expectedYield: "5 ton/acre Hay",
    repaymentSource: "Cattle Sales",
    cropInsurance: "No",
    bankName: "Rural Community Bank",
    accountNumber: "765432109",
    routingNumber: "345678901",
    creditScore: 680,
    agree: true
  },
  {
    fullName: "James Wilson",
    ssn: "567-89-0123",
    dob: "1972-07-18",
    phone: "(555) 567-8901",
    email: "james.wilson@example.com",
    residentialAddress: "890 Vineyard Way, Wineland, ST 45678",
    mailingAddress: "PO Box 890, Wineland, ST 45678",
    citizenshipStatus: "US Citizen",
    businessName: "Wilson Vineyards",
    entityType: "Corporation",
    ein: "45-6789012",
    usdaFarmNumber: "USDA456789",
    farmLocation: "890 Vineyard Way, Wineland, ST 45678",
    yearsInOperation: 12,
    annualIncome: 220000,
    previousLoans: "Yes - Agricultural Mortgage 2019",
    landStatus: "Owned",
    landSize: 150,
    crops: ["Grapes"],
    areaPerCrop: "150 acres",
    irrigationType: "Drip",
    equipmentOwned: "Tractor, Harvester, Wine Press",
    soilType: "Volcanic",
    practices: "Organic Certification",
    loanAmount: 180000,
    loanPurpose: "Winery Equipment",
    loanTerm: "8 years",
    loanType: "Facility Loan",
    disbursementDate: "2023-09-01",
    expectedYield: "5 tons/acre",
    repaymentSource: "Wine Sales",
    cropInsurance: "Yes - Crop Revenue Coverage",
    bankName: "Vintners Trust",
    accountNumber: "654321098",
    routingNumber: "456789012",
    creditScore: 750,
    agree: true
},
{
    fullName: "Emma Thompson",
    ssn: "678-90-1234",
    dob: "1985-04-25",
    phone: "(555) 678-9012",
    email: "emma.thompson@example.com",
    residentialAddress: "345 Berry Lane, Fruitvale, ST 56789",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Thompson Berry Farm",
    entityType: "Family Farm",
    ein: "56-7890123",
    usdaFarmNumber: "USDA567890",
    farmLocation: "345 Berry Lane, Fruitvale, ST 56789",
    yearsInOperation: 7,
    annualIncome: 85000,
    previousLoans: "No",
    landStatus: "Inherited",
    landSize: 50,
    crops: ["Strawberries"],
    areaPerCrop: "20 acres Strawberries, 15 acres each Blue/Rasp",
    irrigationType: "Micro-Sprinkler",
    equipmentOwned: "Tractor, Picker",
    soilType: "Sandy",
    practices: "Integrated Pest Management",
    loanAmount: 35000,
    loanPurpose: "Greenhouse Construction",
    loanTerm: "5 years",
    loanType: "Improvement Loan",
    disbursementDate: "2023-10-15",
    expectedYield: "15,000 lbs/acre Strawberries",
    repaymentSource: "U-Pick Operations",
    cropInsurance: "Yes - AGR-Lite",
    bankName: "Community First Bank",
    accountNumber: "543210987",
    routingNumber: "567890123",
    creditScore: 710,
    agree: true
},
{
    fullName: "Michael Brown",
    ssn: "789-01-2345",
    dob: "1968-09-12",
    phone: "(555) 789-0123",
    email: "michael.brown@example.com",
    residentialAddress: "678 Dairy Dr, Milkville, ST 67890",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Brown Dairy Farms",
    entityType: "LLC",
    ein: "67-8901234",
    usdaFarmNumber: "USDA678901",
    farmLocation: "678 Dairy Dr, Milkville, ST 67890",
    yearsInOperation: 22,
    annualIncome: 320000,
    previousLoans: "Yes - Multiple FSA Loans",
    landStatus: "Owned",
    landSize: 300,
    crops: ["Corn Silage"],
    areaPerCrop: "200 acres Corn, 100 acres Alfalfa",
    irrigationType: "Center Pivot",
    equipmentOwned: "Tractor, Baler, Milking Parlor",
    soilType: "Clay",
    practices: "Precision Feeding",
    loanAmount: 150000,
    loanPurpose: "Milk Processing Equipment",
    loanTerm: "10 years",
    loanType: "Value-Added Producer Grant",
    disbursementDate: "2023-11-01",
    expectedYield: "25 ton/acre Corn Silage",
    repaymentSource: "Dairy Product Sales",
    cropInsurance: "Yes - Livestock Gross Margin",
    bankName: "Dairyland Credit Union",
    accountNumber: "432109876",
    routingNumber: "678901234",
    creditScore: 695,
    agree: true
},
{
    fullName: "Olivia Davis",
    ssn: "890-12-3456",
    dob: "1990-12-05",
    phone: "(555) 890-1234",
    email: "olivia.davis@example.com",
    residentialAddress: "901 Organic Ave, Greentown, ST 78901",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Davis Organic Produce",
    entityType: "Sole Proprietorship",
    ein: "78-9012345",
    usdaFarmNumber: "USDA789012",
    farmLocation: "901 Organic Ave, Greentown, ST 78901",
    yearsInOperation: 5,
    annualIncome: 68000,
    previousLoans: "Yes - Microloan 2021",
    landStatus: "Leased",
    landSize: 30,
    crops: ["Tomatoes"],
    areaPerCrop: "7-8 acres each",
    irrigationType: "Drip Tape",
    equipmentOwned: "Walk-behind Tractor",
    soilType: "Loamy Sand",
    practices: "Certified Organic",
    loanAmount: 25000,
    loanPurpose: "Cooling Storage",
    loanTerm: "3 years",
    loanType: "Microloan",
    disbursementDate: "2023-12-01",
    expectedYield: "Varies by crop",
    repaymentSource: "Farmers Markets",
    cropInsurance: "Yes - Whole Farm Revenue Protection",
    bankName: "Green Growth Credit",
    accountNumber: "321098765",
    routingNumber: "789012345",
    creditScore: 730,
    agree: true
},
{
    fullName: "William Miller",
    ssn: "901-23-4567",
    dob: "1978-06-30",
    phone: "(555) 901-2345",
    email: "william.miller@example.com",
    residentialAddress: "234 Grain Blvd, Breadbasket, ST 89012",
    mailingAddress: "PO Box 234, Breadbasket, ST 89012",
    citizenshipStatus: "US Citizen",
    businessName: "Miller Grain Co.",
    entityType: "Partnership",
    ein: "89-0123456",
    usdaFarmNumber: "USDA890123",
    farmLocation: "234 Grain Blvd, Breadbasket, ST 89012",
    yearsInOperation: 18,
    annualIncome: 280000,
    previousLoans: "Yes - Operating Loans annually",
    landStatus: "Owned/Leased Mix",
    landSize: 2000,
    crops: ["Barley"],
    areaPerCrop: "800 acres Wheat, 600 each Barley/Oats",
    irrigationType: "Dryland Farming",
    equipmentOwned: "Combine, Grain Cart, Semi Trucks",
    soilType: "Silt Loam",
    practices: "No-Till",
    loanAmount: 300000,
    loanPurpose: "Grain Storage Expansion",
    loanTerm: "7 years",
    loanType: "Storage Facility Loan",
    disbursementDate: "2024-01-15",
    expectedYield: "60 bu/acre Wheat",
    repaymentSource: "Commodity Sales",
    cropInsurance: "Yes - Revenue Protection",
    bankName: "Plains State Bank",
    accountNumber: "210987654",
    routingNumber: "890123456",
    creditScore: 715,
    agree: true
},
{
    fullName: "Sophia Anderson",
    ssn: "012-34-5678",
    dob: "1983-02-14",
    phone: "(555) 012-3456",
    email: "sophia.anderson@example.com",
    residentialAddress: "567 Flower Rd, Blossomville, ST 90123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Anderson Blooms",
    entityType: "LLC",
    ein: "90-1234567",
    usdaFarmNumber: "USDA901234",
    farmLocation: "567 Flower Rd, Blossomville, ST 90123",
    yearsInOperation: 10,
    annualIncome: 115000,
    previousLoans: "Yes - Small Business Loan 2020",
    landStatus: "Owned",
    landSize: 40,
    crops: ["Cut Flowers"],
    areaPerCrop: "40 acres",
    irrigationType: "Drip",
    equipmentOwned: "Greenhouses, Coolers",
    soilType: "Sandy Loam",
    practices: "Sustainable Floriculture",
    loanAmount: 65000,
    loanPurpose: "Greenhouse Automation",
    loanTerm: "6 years",
    loanType: "Equipment Loan",
    disbursementDate: "2024-02-01",
    expectedYield: "Varies by variety",
    repaymentSource: "Wholesale Flower Markets",
    cropInsurance: "No",
    bankName: "Horticultural Credit Union",
    accountNumber: "109876543",
    routingNumber: "901234567",
    creditScore: 740,
    agree: true
},
{
    fullName: "Benjamin Taylor",
    ssn: "123-45-6780",
    dob: "1960-11-08",
    phone: "(555) 123-4560",
    email: "benjamin.taylor@example.com",
    residentialAddress: "890 Ranch Trail, Cattleland, ST 01234",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Taylor Beef Ranch",
    entityType: "Family Trust",
    ein: "01-2345678",
    usdaFarmNumber: "USDA012345",
    farmLocation: "890 Ranch Trail, Cattleland, ST 01234",
    yearsInOperation: 35,
    annualIncome: 410000,
    previousLoans: "Multiple FSA Loans",
    landStatus: "Owned",
    landSize: 2500,
    crops: ["Pasture", "Hay"],
    areaPerCrop: "2000 acres Pasture, 500 acres Hay",
    irrigationType: "Flood",
    equipmentOwned: "Tractors, Cattle Equipment",
    soilType: "Clay Loam",
    practices: "Rotational Grazing",
    loanAmount: 200000,
    loanPurpose: "Feedlot Expansion",
    loanTerm: "10 years",
    loanType: "Farm Ownership Loan",
    disbursementDate: "2024-03-15",
    expectedYield: "N/A",
    repaymentSource: "Beef Sales",
    cropInsurance: "Yes - Livestock Risk Protection",
    bankName: "Cattlemen's Bank",
    accountNumber: "098765432",
    routingNumber: "012345678",
    creditScore: 705,
    agree: true
},
{
    fullName: "Ava Martinez",
    ssn: "234-56-7891",
    dob: "1987-07-22",
    phone: "(555) 234-5671",
    email: "ava.martinez@example.com",
    residentialAddress: "123 Spice Lane, Herbtown, ST 12340",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Martinez Herb Farms",
    entityType: "Sole Proprietorship",
    ein: "12-3456780",
    usdaFarmNumber: "USDA123450",
    farmLocation: "123 Spice Lane, Herbtown, ST 12340",
    yearsInOperation: 6,
    annualIncome: 92000,
    previousLoans: "Yes - Beginning Farmer Loan",
    landStatus: "Leased",
    landSize: 25,
    crops: ["Basil"],
    areaPerCrop: "6-7 acres each",
    irrigationType: "Drip",
    equipmentOwned: "Small Tractors",
    soilType: "Loam",
    practices: "Organic Methods",
    loanAmount: 40000,
    loanPurpose: "Essential Oil Distillery",
    loanTerm: "5 years",
    loanType: "Value-Added Producer Grant",
    disbursementDate: "2024-04-01",
    expectedYield: "Varies by herb",
    repaymentSource: "Herb Product Sales",
    cropInsurance: "Yes - Whole Farm Revenue Protection",
    bankName: "Community Development Bank",
    accountNumber: "987654321",
    routingNumber: "123456780",
    creditScore: 725,
    agree: true
},
{
    fullName: "Mason Robinson",
    ssn: "345-67-8902",
    dob: "1975-04-18",
    phone: "(555) 345-6782",
    email: "mason.robinson@example.com",
    residentialAddress: "456 Nut Grove, Orchardville, ST 23401",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Robinson Nut Farms",
    entityType: "LLC",
    ein: "23-4567891",
    usdaFarmNumber: "USDA234561",
    farmLocation: "456 Nut Grove, Orchardville, ST 23401",
    yearsInOperation: 14,
    annualIncome: 180000,
    previousLoans: "Yes - Tree Planting Loan 2015",
    landStatus: "Owned",
    landSize: 120,
    crops: ["Almonds", "Walnuts"],
    areaPerCrop: "70 acres Almonds, 50 acres Walnuts",
    irrigationType: "Micro-Sprinkler",
    equipmentOwned: "Shakers, Harvesters",
    soilType: "Sandy Loam",
    practices: "Integrated Pest Management",
    loanAmount: 95000,
    loanPurpose: "Processing Equipment",
    loanTerm: "8 years",
    loanType: "Equipment Loan",
    disbursementDate: "2024-05-15",
    expectedYield: "2000 lbs/acre Almonds",
    repaymentSource: "Nut Sales",
    cropInsurance: "Yes - Actual Production History",
    bankName: "Orchard Financial",
    accountNumber: "876543219",
    routingNumber: "234567801",
    creditScore: 760,
    agree: true
},
{
    fullName: "Charlotte Clark",
    ssn: "456-78-9013",
    dob: "1992-09-27",
    phone: "(555) 456-7893",
    email: "charlotte.clark@example.com",
    residentialAddress: "789 Mushroom Circle, Fungitown, ST 34012",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Clark Fungiculture",
    entityType: "Sole Proprietorship",
    ein: "34-5678902",
    usdaFarmNumber: "USDA345672",
    farmLocation: "789 Mushroom Circle, Fungitown, ST 34012",
    yearsInOperation: 4,
    annualIncome: 75000,
    previousLoans: "No",
    landStatus: "Leased Building",
    landSize: 5,
    crops: ["Oyster Mushrooms"],
    areaPerCrop: "Indoor cultivation",
    irrigationType: "Misting System",
    equipmentOwned: "Growing Chambers",
    soilType: "N/A",
    practices: "Controlled Environment Agriculture",
    loanAmount: 50000,
    loanPurpose: "Expansion to New Facility",
    loanTerm: "5 years",
    loanType: "Beginning Farmer Loan",
    disbursementDate: "2024-06-01",
    expectedYield: "Multiple crops/year",
    repaymentSource: "Restaurant Wholesale",
    cropInsurance: "No",
    bankName: "Urban Agriculture Credit",
    accountNumber: "765432198",
    routingNumber: "345678012",
    creditScore: 690,
    agree: true
},
{
    fullName: "Ethan Rodriguez",
    ssn: "567-89-0124",
    dob: "1980-12-15",
    phone: "(555) 567-8904",
    email: "ethan.rodriguez@example.com",
    residentialAddress: "123 Citrus Ave, Orangetown, ST 40123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Rodriguez Citrus",
    entityType: "Partnership",
    ein: "45-6789013",
    usdaFarmNumber: "USDA456783",
    farmLocation: "123 Citrus Ave, Orangetown, ST 40123",
    yearsInOperation: 16,
    annualIncome: 240000,
    previousLoans: "Yes - Freeze Protection Loan 2018",
    landStatus: "Owned",
    landSize: 200,
    crops: ["Grapefruit"],
    areaPerCrop: "100 acres Oranges, 50 each Lemons/Grapefruit",
    irrigationType: "Micro-Sprinkler",
    equipmentOwned: "Tractors, Sprayers",
    soilType: "Sandy",
    practices: "Integrated Pest Management",
    loanAmount: 125000,
    loanPurpose: "Frost Protection System",
    loanTerm: "7 years",
    loanType: "Emergency Loan",
    disbursementDate: "2024-07-15",
    expectedYield: "400 boxes/acre Oranges",
    repaymentSource: "Citrus Sales",
    cropInsurance: "Yes - Catastrophic Coverage",
    bankName: "Sunshine State Bank",
    accountNumber: "654321987",
    routingNumber: "456780123",
    creditScore: 710,
    agree: true
},
{
    fullName: "Amelia Lewis",
    ssn: "678-90-1235",
    dob: "1973-05-08",
    phone: "(555) 678-9015",
    email: "amelia.lewis@example.com",
    residentialAddress: "456 Apiary Lane, Beecity, ST 50123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Lewis Honey Farms",
    entityType: "Sole Proprietorship",
    ein: "56-7890124",
    usdaFarmNumber: "USDA567894",
    farmLocation: "456 Apiary Lane, Beecity, ST 50123",
    yearsInOperation: 12,
    annualIncome: 110000,
    previousLoans: "Yes - Small Equipment Loan 2020",
    landStatus: "Owned",
    landSize: 80,
    crops: ["Clover"],
    areaPerCrop: "For bee forage",
    irrigationType: "None",
    equipmentOwned: "Beehives, Extractor",
    soilType: "Varied",
    practices: "Sustainable Beekeeping",
    loanAmount: 45000,
    loanPurpose: "Honey Processing Facility",
    loanTerm: "5 years",
    loanType: "Value-Added Producer Grant",
    disbursementDate: "2024-08-01",
    expectedYield: "100 lbs/hive",
    repaymentSource: "Honey Product Sales",
    cropInsurance: "No",
    bankName: "Local Harvest Credit",
    accountNumber: "543219876",
    routingNumber: "567801234",
    creditScore: 735,
    agree: true
},
{
    fullName: "Alexander Walker",
    ssn: "789-01-2346",
    dob: "1965-10-30",
    phone: "(555) 789-0126",
    email: "alexander.walker@example.com",
    residentialAddress: "789 Timber Rd, Forestville, ST 60123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Walker Tree Farm",
    entityType: "Family Business",
    ein: "67-8901235",
    usdaFarmNumber: "USDA678905",
    farmLocation: "789 Timber Rd, Forestville, ST 60123",
    yearsInOperation: 28,
    annualIncome: 175000,
    previousLoans: "Yes - Replanting Loan 2015",
    landStatus: "Owned",
    landSize: 150,
    crops: ["Hardwood Saplings"],
    areaPerCrop: "100 acres Christmas, 50 acres Hardwood",
    irrigationType: "Drip",
    equipmentOwned: "Tractor, Baler",
    soilType: "Acidic",
    practices: "Sustainable Forestry",
    loanAmount: 85000,
    loanPurpose: "New Varieties Planting",
    loanTerm: "10 years",
    loanType: "Tree Planting Loan",
    disbursementDate: "2024-09-15",
    expectedYield: "1000 trees/acre",
    repaymentSource: "Tree Sales",
    cropInsurance: "Yes - Nursery Crop Insurance",
    bankName: "Forest Credit Union",
    accountNumber: "432198765",
    routingNumber: "678012345",
    creditScore: 745,
    agree: true
},
{
    fullName: "Mia Hall",
    ssn: "890-12-3457",
    dob: "1988-03-12",
    phone: "(555) 890-1237",
    email: "mia.hall@example.com",
    residentialAddress: "123 Hops Way, Brewtown, ST 70123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Hall Hops Farm",
    entityType: "LLC",
    ein: "78-9012346",
    usdaFarmNumber: "USDA789016",
    farmLocation: "123 Hops Way, Brewtown, ST 70123",
    yearsInOperation: 6,
    annualIncome: 140000,
    previousLoans: "Yes - Specialty Crop Loan 2021",
    landStatus: "Leased",
    landSize: 60,
    crops: ["Hops"],
    areaPerCrop: "60 acres",
    irrigationType: "Drip",
    equipmentOwned: "Trellis System",
    soilType: "Loam",
    practices: "Organic Certification",
    loanAmount: 90000,
    loanPurpose: "Processing Equipment",
    loanTerm: "6 years",
    loanType: "Specialty Crop Loan",
    disbursementDate: "2024-10-01",
    expectedYield: "1800 lbs/acre",
    repaymentSource: "Craft Brewery Contracts",
    cropInsurance: "Yes - Specialty Crop Insurance",
    bankName: "Brewers Financial",
    accountNumber: "321987654",
    routingNumber: "780123456",
    creditScore: 725,
    agree: true
},
{
    fullName: "Lucas Allen",
    ssn: "901-23-4568",
    dob: "1970-08-24",
    phone: "(555) 901-2348",
    email: "lucas.allen@example.com",
    residentialAddress: "456 Aqua Farm, Fishtown, ST 80123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Allen Aquafarms",
    entityType: "Corporation",
    ein: "89-0123457",
    usdaFarmNumber: "USDA890127",
    farmLocation: "456 Aqua Farm, Fishtown, ST 80123",
    yearsInOperation: 15,
    annualIncome: 210000,
    previousLoans: "Multiple Aquaculture Loans",
    landStatus: "Owned",
    landSize: 40,
    crops: ["Tilapia", "Catfish"],
    areaPerCrop: "20 ponds each",
    irrigationType: "Water Recirculation",
    equipmentOwned: "Ponds, Aeration",
    soilType: "N/A",
    practices: "Sustainable Aquaculture",
    loanAmount: 110000,
    loanPurpose: "Processing Facility",
    loanTerm: "7 years",
    loanType: "Aquaculture Loan",
    disbursementDate: "2024-11-15",
    expectedYield: "5000 lbs/pond",
    repaymentSource: "Fish Sales",
    cropInsurance: "Yes - Aquaculture Insurance",
    bankName: "Marine Credit Union",
    accountNumber: "219876543",
    routingNumber: "890123457",
    creditScore: 695,
    agree: true
},
{
    fullName: "Harper Young",
    ssn: "012-34-5679",
    dob: "1982-01-17",
    phone: "(555) 012-3459",
    email: "harper.young@example.com",
    residentialAddress: "789 Lavender Ln, Aromatown, ST 90123",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Young Aromatics",
    entityType: "Sole Proprietorship",
    ein: "90-1234568",
    usdaFarmNumber: "USDA901238",
    farmLocation: "789 Lavender Ln, Aromatown, ST 90123",
    yearsInOperation: 9,
    annualIncome: 95000,
    previousLoans: "Yes - Value-Added Loan 2020",
    landStatus: "Owned",
    landSize: 35,
    crops: ["Lavender"],
    areaPerCrop: "15 acres Lavender, 10 each Rosemary/Sage",
    irrigationType: "Drip",
    equipmentOwned: "Distillation Equipment",
    soilType: "Well-Drained",
    practices: "Organic Methods",
    loanAmount: 55000,
    loanPurpose: "Essential Oil Expansion",
    loanTerm: "5 years",
    loanType: "Value-Added Producer Grant",
    disbursementDate: "2024-12-01",
    expectedYield: "Varies by herb",
    repaymentSource: "Aromatherapy Products",
    cropInsurance: "Yes - Whole Farm Revenue Protection",
    bankName: "Botanical Financial",
    accountNumber: "198765432",
    routingNumber: "901234568",
    creditScore: 715,
    agree: true
},
{
    fullName: "Evelyn King",
    ssn: "123-45-6781",
    dob: "1977-06-03",
    phone: "(555) 123-4561",
    email: "evelyn.king@example.com",
    residentialAddress: "123 Pumpkin Patch, Harvestville, ST 01235",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "King's Fall Harvest",
    entityType: "Family Farm",
    ein: "01-2345679",
    usdaFarmNumber: "USDA012349",
    farmLocation: "123 Pumpkin Patch, Harvestville, ST 01235",
    yearsInOperation: 14,
    annualIncome: 125000,
    previousLoans: "Yes - Seasonal Operating Loans",
    landStatus: "Owned",
    landSize: 100,
    crops: ["Pumpkins"],
    areaPerCrop: "50 acres Pumpkins, 25 each Squash/Gourds",
    irrigationType: "Drip",
    equipmentOwned: "Tractor, Harvesters",
    soilType: "Loam",
    practices: "Agritourism Focus",
    loanAmount: 60000,
    loanPurpose: "Farm Stand Construction",
    loanTerm: "5 years",
    loanType: "Agritourism Loan",
    disbursementDate: "2025-01-15",
    expectedYield: "1000 pumpkins/acre",
    repaymentSource: "Fall Festival Revenue",
    cropInsurance: "Yes - Adjusted Gross Revenue",
    bankName: "Harvest Credit Union",
    accountNumber: "098765431",
    routingNumber: "012345679",
    creditScore: 730,
    agree: true
},
{
    fullName: "Henry Scott",
    ssn: "234-56-7892",
    dob: "1963-09-28",
    phone: "(555) 234-5672",
    email: "henry.scott@example.com",
    residentialAddress: "456 Maple Syrup Rd, Sweetville, ST 12350",
    mailingAddress: "Same as residential",
    citizenshipStatus: "US Citizen",
    businessName: "Scott's Maple Products",
    entityType: "Partnership",
    ein: "12-3456781",
    usdaFarmNumber: "USDA123460",
    farmLocation: "456 Maple Syrup Rd, Sweetville, ST 12350",
    yearsInOperation: 30,
    annualIncome: 195000,
    previousLoans: "Multiple Equipment Loans",
    landStatus: "Owned",
    landSize: 500,
    crops: ["Sugar Maples"],
    areaPerCrop: "500 acres",
    irrigationType: "None",
    equipmentOwned: "Evaporators, Tapping Equipment",
    soilType: "Varied",
    practices: "Sustainable Tapping",
    loanAmount: 85000,
    loanPurpose: "Sugar House Upgrade",
    loanTerm: "7 years",
    loanType: "Facility Improvement Loan",
    disbursementDate: "2025-02-01",
    expectedYield: "1 gallon/tap",
    repaymentSource: "Maple Product Sales",
    cropInsurance: "Yes - Noninsured Crop Assistance",
    bankName: "Northwoods Bank",
    accountNumber: "987654320",
    routingNumber: "123456781",
    creditScore: 710,
    agree: true
}
]



 export const tokens = [
    {
      crop: "Wheat",
      quantity: "500 bushel",
      amount: "$25,000",
      type: "Pre-Harvest",
      date: "Apr 1, 2025",
      status: "Requested",
    },
    {
      crop: "Rice",
      quantity: "800 bushel",
      amount: "$40,000",
      type: "Pre-Harvest",
      date: "Mar 28, 2025",
      status: "Created",
    },
    {
      crop: "Corn",
      quantity: "1200 bushel",
      amount: "$60,000",
      type: "Post-Harvest",
      date: "Mar 25, 2025",
      status: "Approved",
    },
    {
      crop: "Soybean",
      quantity: "600 bushel",
      amount: "$35,000",
      type: "Pre-Harvest",
      date: "Mar 10, 2025",
      status: "Rejected",
    },
    {
      crop: "Barley",
      quantity: "400 bushel",
      amount: "$20,000",
      type: "Post-Harvest",
      date: "Mar 5, 2025",
      status: "Created",
    },
    {
      crop: "Potato",
      quantity: "2000 bushel",
      amount: "$30,000",
      type: "Post-Harvest",
      date: "Feb 15, 2025",
      status: "Completed",
    },
  ];